import { Location, Dish } from '@/types/types';

const dishLocations: Record<string, Location[]> = {
  Siopao: [
    {
      name: "Roberto's Siopao",
      x: 500,
      y: 300,
      description: "Famous for their Siopao since 1978",
      iconType: "siopao",
      siopaoVariant: 1,
      address: "Rizal Street, La Paz Public Market, La Paz, Iloilo City",
      openHours: "10:00 AM - 9:00 PM",
      priceRange: "₱200-400",
      photos: [
        "/location-photos/robertos-1.jpg",
        "/location-photos/robertos-2.jpg",
        "/location-photos/robertos-3.jpg",
        "/location-photos/robertos-4.jpg",
      ],
    },
    {
      name: "Deco's",
      x: 700,
      y: 400,
      description: "Home of the King-sized Siopao",
      iconType: "siopao",
      siopaoVariant: 2,
      address: "Iznart Street, Iloilo City",
      openHours: "8:00 AM - 8:00 PM",
      priceRange: "₱150-300",
    },
    {
      name: "Kusina ni Mama",
      x: 500,
      y: 600,
      description: "Traditional homemade Siopao",
      iconType: "siopao",
      siopaoVariant: 3,
      address: "JM Basa Street, Iloilo City",
      openHours: "9:00 AM - 7:00 PM",
      priceRange: "₱100-200",
    },
  ],
  "La Paz Batchoy": [
    {
      name: "Ted's Oldtimer La Paz Batchoy",
      x: 450,
      y: 350,
      description: "Original La Paz Batchoy since 1945",
      iconType: "restaurant",
      iconUrl: "/location-markers/batchoy-marker-1.png",
      address: "La Paz Public Market, Iloilo City",
      openHours: "7:00 AM - 8:00 PM",
      priceRange: "₱100-200",
    },
    {
      name: "Deco's La Paz Batchoy",
      x: 650,
      y: 450,
      description: "Famous for their special batchoy recipe",
      iconType: "restaurant",
      iconUrl: "/location-markers/batchoy-marker-2.png",
      address: "Rizal Street, La Paz, Iloilo City",
      openHours: "8:00 AM - 9:00 PM",
      priceRange: "₱120-220",
    },
  ],
  Cansi: [
    {
      name: "Sharyn's Cansi House",
      x: 550,
      y: 500,
      description: "Authentic Ilonggo Cansi since 1990",
      iconType: "restaurant",
      iconUrl: "/cansi-1.png",
      address: "Molo, Iloilo City",
      openHours: "10:00 AM - 8:00 PM",
      priceRange: "₱250-450",
    },
  ],
  Inasal: [
    {
      name: "Manokan Country",
      x: 480,
      y: 320,
      description: "Famous chicken inasal stalls",
      iconType: "restaurant",
      iconUrl: "/inasal-1.png",
      address: "Reclamation Area, Bacolod City",
      openHours: "10:00 AM - 10:00 PM",
      priceRange: "₱150-300",
    },
    {
      name: "Aida's Chicken",
      x: 600,
      y: 380,
      description: "Authentic Bacolod-style Chicken Inasal",
      iconType: "restaurant",
      iconUrl: "/inasal-2.png",
      address: "Lacson Street, Bacolod City",
      openHours: "10:00 AM - 9:00 PM",
      priceRange: "₱180-350",
    },
  ],
  KBL: [
    {
      name: "Tatoy's Manokan and Seafoods",
      x: 520,
      y: 420,
      description: "Famous for traditional Ilonggo dishes including KBL",
      iconType: "restaurant",
      iconUrl: "/kbl-1.png",
      address: "Villa Beach, Iloilo City",
      openHours: "10:00 AM - 9:00 PM",
      priceRange: "₱200-500",
    },
  ],
  "Pancit Molo": [
    {
      name: "Mama's Kitchen",
      x: 580,
      y: 340,
      description: "Home of authentic Pancit Molo",
      iconType: "restaurant",
      iconUrl: "/molo-1.png",
      address: "Molo Plaza, Iloilo City",
      openHours: "9:00 AM - 8:00 PM",
      priceRange: "₱120-250",
    },
    {
      name: "Original Pancit Molo House",
      x: 490,
      y: 470,
      description: "Serving traditional Ilonggo Pancit Molo",
      iconType: "restaurant",
      iconUrl: "/molo-2.png",
      address: "Molo District, Iloilo City",
      openHours: "10:00 AM - 7:00 PM",
      priceRange: "₱100-200",
    },
  ],
};

const Dishes: Dish[] = [
  {
    name: "Siopao",
    image: "/images/filter-dish/siopao.png",
    images: [
      "/images/filter-dish/siopao.png",
      "/images/filter-dish/inasal.jpg",
      "/images/filter-dish/cansi.jpg",
      "/images/filter-dish/kbl.jpg",
      "/images/filter-dish/pancit_molo.jpg",
    ],
    description:
      "Bao Zi (包子), also known as mantou when unfilled, is a staple food among Chinese worldwide. Hence, there are Baozi versions in Singapore, HK, Vietnam, the Philippines, and other countries with strong Chinese influence. The exact origins of siopao in the Philippines are not well-documented, but Chinese vendors likely sold it along with noodles as early as the 1600s.",
    tagline: "Philippine Steamed Bun",
    href: "/food-map",
    locations: dishLocations["Siopao"],
  },
  {
    name: "La Paz Batchoy",
    image: "/images/filter-dish/batchoy.webp",
    images: [
      "/images/filter-dish/batchoy.webp",
      "/images/filter-dish/kbl.jpg",
      "/images/filter-dish/pancit_molo.jpg",
    ],
    description:
      "A hearty noodle soup with pork, liver, and chicharrón, La Paz Batchoy is a famous Ilonggo delicacy originating from La Paz, Iloilo.",
    tagline: "Ilonggo Noodle Soup",
    href: "/food-map",
    locations: dishLocations["La Paz Batchoy"],
  },
  {
    name: "Cansi",
    image: "/images/filter-dish/cansi.jpg",
    images: [
      "/images/filter-dish/cansi.jpg",
      "/images/filter-dish/siopao.png",
      "/images/filter-dish/inasal.jpg",
      "/images/filter-dish/batchoy.webp",
    ],
    description:
      "Cansi is a famous Ilonggo beef soup known for its rich, sour taste due to the batwan fruit, a local ingredient unique to Western Visayas.",
    tagline: "Beef Bone Marrow Soup",
    href: "/food-map",
    locations: dishLocations["Cansi"],
  },
  {
    name: "Inasal",
    image: "/images/filter-dish/inasal.jpg",
    images: [
      "/images/filter-dish/inasal.jpg",
      "/images/filter-dish/cansi.jpg",
      "/images/filter-dish/siopao.png",
      "/images/filter-dish/pancit_molo.jpg",
    ],
    description:
      "Chicken Inasal is a famous Bacolod-style grilled chicken marinated in vinegar, calamansi, and spices, served with annatto oil and garlic rice.",
    tagline: "Bacolod Grilled Chicken",
    href: "/food-map",
    locations: dishLocations["Inasal"],
  },
  {
    name: "KBL",
    image: "/images/filter-dish/kbl.jpg",
    images: [
      "/images/filter-dish/kbl.jpg",
      "/images/filter-dish/cansi.jpg",
      "/images/filter-dish/batchoy.webp",
    ],
    description:
      "KBL (Kadyos, Baboy, Langka) is a traditional Ilonggo stew made with pigeon peas, pork, and unripe jackfruit, flavored with batwan fruit.",
    tagline: "Pork & Jackfruit Stew",
    href: "/food-map",
    locations: dishLocations["KBL"],
  },
  {
    name: "Pancit Molo",
    image: "/images/filter-dish/pancit_molo.jpg",
    images: [
      "/images/filter-dish/pancit_molo.jpg",
      "/images/filter-dish/inasal.jpg",
      "/images/filter-dish/siopao.png",
      "/images/filter-dish/kbl.jpg",
    ],
    description:
      "A dumpling soup originating from Molo, Iloilo, Pancit Molo consists of meat-filled wontons in a flavorful chicken broth.",
    tagline: "Ilonggo Wonton Soup",
    href: "/food-map",
    locations: dishLocations["Pancit Molo"],
  },
];
export default Dishes;
