import { Location } from "@/types/types";

export const LocationData: Record<string, Location[]> = {
  Siopao: [
    {
      name: "Robertos",
      address: "61 JM Basa St, Iloilo City Proper, Iloilo City, Iloilo",
      x: 650,
      y: 300,
      openHours: "8:00 AM - 5:30 PM",
      priceRange: "₱1-200",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Dinagyang Siopao",
      address:
        "MGP6+FJM, Fegueroa St. Corner Bonifacio, Villa Arevalo Dist, Iloilo City",
      x: 700,
      y: 400,
      openHours: "7:00 AM - 9:00 PM",
      priceRange: "₱1-100",
      mapLink: "",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Nang Pat's Siopawan",
      address: "MGP6+GM5, Bonifacio St, Villa Arevalo District, Iloilo City",
      x: 550,
      y: 600,
      openHours: "6:00 AM - 10:30 PM",
      priceRange: "₱1-100",
      mapLink: "",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Deocampo Barquillos",
      address: "46 Santa Isabel St, Jaro, Iloilo City",
      x: 500,
      y: 600,
      openHours: "7:00 AM - 6:00 PM",
      priceRange: "₱1-100",
      mapLink: "",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
  ],
  Batchoy: [
    {
      name: "Netong’s",
      address: "La Paz Public Market",
      x: 500,
      y: 300,
      openHours: "9:30 AM - 11:00 PM",
      priceRange: "₱100-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Inggo’s",
      address: "Magsaysay Village, La Paz, Iloilo City",
      x: 520,
      y: 310,
      openHours: "6:00 AM - 8:00 PM",
      priceRange: "₱1-200",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Deco’s",
      address:
        "LaSalette Building, Valeria St, Iloilo City Proper, Iloilo City, 5000 Iloilo",
      x: 540,
      y: 320,
      openHours: "9:00 AM - 7:00 PM",
      priceRange: "₱1-200",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Alicia’s",
      address:
        "Red Square Building, San Jose St, Mandurriao, Iloilo City, 5000 Iloilo",
      x: 560,
      y: 330,
      openHours: "7:00 AM - 11:00 PM",
      priceRange: "₱100-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Ted’s",
      address: "SM City, Iloilo Driveway, Mandurriao, Iloilo City, Iloilo",
      x: 580,
      y: 340,
      openHours: "10:00 AM - 9:00 PM",
      priceRange: "₱200-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Doming's",
      address: "Benigno Aquino Ave, Diversion Rd, Iloilo City, 5000 Iloilo",
      x: 600,
      y: 350,
      openHours: "10:00 AM - 7:30 PM",
      priceRange: "₱1-200",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
  ],
  Cansi: [
    {
      name: "Patpat’s Kansi",
      address: "113 Burgos St, Jaro, Iloilo City, Iloilo",
      x: 620,
      y: 360,
      openHours: "9:00 AM - 8:00 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Tatay Andres",
      address:
        "The Grove, Esplanade One, Tabucan, Mandurriao, Iloilo City, Iloilo",
      x: 640,
      y: 370,
      openHours: "12:00 AM - 11:59 PM",
      priceRange: "₱100-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Pedbacs",
      address: "208 R.Mapa St, Mandurriao, Iloilo City, 5000 Iloilo",
      x: 660,
      y: 380,
      openHours: "6:00 AM - 9:00 PM",
      priceRange: "₱100-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
  ],
  KBL: [
    {
      name: "Doming's Talabahan",
      address: "J7V3+RCW, National Hwy, Miagao, Iloilo",
      x: 680,
      y: 390,
      openHours: "8:00 AM - 8:00 PM",
      priceRange: "₱200-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Punot",
      address:
        "Riverside Boardwalk, Diversion Rd, Mandurriao, Iloilo City, 5000 Iloilo",
      x: 700,
      y: 400,
      openHours: "11:00 AM - 9:00 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Breakthrough",
      address: "MGH8+WWQ, Villa Arevalo District, Iloilo City, Iloilo",
      x: 720,
      y: 410,
      openHours: "9:00 AM - 9:00 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
  ],

  PancitMolo: [
    {
      name: "Kap Ising’s",
      address:
        "Atria Park District, Benigno Aquino Ave, Mandurriao, Iloilo City, 5000 Iloilo",
      x: 740,
      y: 420,
      openHours: "8:30 AM - 8:00 PM",
      priceRange: "₱100-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Panaderia de Molo",
      address: "Avanceña St, Molo, Iloilo City, 5000 Iloilo",
      x: 760,
      y: 430,
      openHours: "9:00 AM - 5:00 PM",
      priceRange: "₱100-300",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Hotel del Rio",
      address: "M.H. del Pilar St., Molo, Iloilo City",
      x: 780,
      y: 440,
      openHours: "12:00 AM - 11:59 PM",
      priceRange: "₱100-400",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
  ],
  ChickenInasal: [
    {
      name: "Barrio Inasal",
      address:
        "PH52+2XH, Benigno Aquino Ave Service Rd, Mandurriao, Iloilo City, 5000 Iloilo",
      x: 800,
      y: 450,
      openHours: "11:00 AM - 2:00 PM, 5:00 PM - 10:00 PM",
      priceRange: "₱100-600",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Arturo’s Barbeque",
      address:
        "St. Joseph School Iloilo [Back Gate], San Rafael, Mandurriao, Iloilo City",
      x: 820,
      y: 460,
      openHours: "10:00 AM - 10:00 PM",
      priceRange: "₱100-300",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Chicken Sari-Sari",
      address: "50a Commission Civil St, Jaro, Iloilo City, Iloilo",
      x: 840,
      y: 470,
      openHours: "10:30 AM - 9:00 PM",
      priceRange: "₱100-600",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Raac's Unli Rice",
      address: "RGFM+P64, Castilla St, Santa Barbara, Iloilo",
      x: 860,
      y: 480,
      openHours: "9:00 AM - 8:30 PM",
      priceRange: "₱100-300",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
  ],
  Seafood: [
    {
      name: "Tatoy's Manokan and Seafood Restaurant",
      address: "MGJ6+379, Villa Arevalo District, Iloilo City",
      x: 880,
      y: 490,
      openHours: "8:00 AM - 8:00 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Breakthrough Restaurant Iloilo",
      address: "MGH8+WWQ, Villa Arevalo District, Iloilo City",
      x: 900,
      y: 500,
      openHours: "9:00 AM - 9:00 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Erning’s Manokan & Seafood Restaurant",
      address:
        "MGH7+XRV, Baluarte-Calumpang-Villa-Oton Boulevard, Barangay, Villa Arevalo District, Iloilo City, 5000 Iloilo",
      x: 920,
      y: 510,
      openHours: "7:00 AM - 10:00 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Annie's Place",
      address:
        "MGH5+W26, Baluarte - Calumpang - Villa - Oton Blvd, Villa Arevalo District, Iloilo City, 5000 Iloilo",
      x: 940,
      y: 520,
      openHours: "9:00 AM - 9:30 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Bulljack’s Talabahan",
      address: "QH2Q+344, Monfort Blvd, Jaro, Iloilo City, Iloilo",
      x: 960,
      y: 530,
      openHours: "8:00 AM - 9:00 PM",
      priceRange: "₱100-600",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Matmat Talabahan Seafood and Restaurant",
      address:
        "MGH5+WF8, Valuarte-Calumpang, Baluarte - Calumpang - Villa - Oton Blvd, Villa Arevalo District, Iloilo City",
      x: 980,
      y: 540,
      openHours: "6:00 AM - 10:00 PM",
      priceRange: "₱100-600",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
    {
      name: "Igma Seafood Restaurant",
      address: "QH4V+H23 Bito-on, Jaro, Iloilo City",
      x: 1000,
      y: 550,
      openHours: "7:00 AM - 9:00 PM",
      priceRange: "₱100-800",
      mapLink: "https://maps.app.goo.gl/nc9ANGGvnH851Z8A8",
      photos: [
        "/images/location-photos/robertos-1.jpg",
        "/images/location-photos/robertos-2.jpg",
        "/images/location-photos/robertos-3.jpg",
        "/images/location-photos/robertos-4.jpg",
      ],
      iconUrl: "/images/location-markers/batchoy-marker-2.png",
    },
  ],
};
